language: php

matrix:
    include:
        - php: hhvm
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

services:
  - redis-server
  - riak

sudo: false

before_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"extension=redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - composer install -n

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
